### ISSUE TITLE
VS Code Error: Request textDocument/documentLink failed

### ISSUE THREAD

**Issue by mzachdev** [Shopify/theme-tools#276]
**Describe the bug**
With the latest version of Shopify Liquid (VS Code Extension) I now get this error message, which is a Theme Check Language Server issue. I'm running Windows 11. 

The error appears in the Output tab:
```
Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Unresolved alias (the anchor must be set before the alias): .code-workspace
  Code: -32603 
```

On the right hand side a popup appears each time I open any file, the error reads `Request textDocument/documentLink failed.` and the Source: `Shopify Liquid`

When I open VS Code if there are files open, then each file open causes this error message to appear. So there's a cascade of errors that appear in quick succession.

I tried adding this to my VS Code settings, but it caused the server to crash permanently:
```
  "shopifyLiquid.legacyMode": true,
  "themeCheck.onlySingleFileChecks": true,
  "shopifyLiquid.languageServerPath": "windows-path-removed-for-security/theme-check-language-server.bat",
```

**Debugging information**
 - OS Windows 11 (latest)
 - Shopify Liquid v2.0.0
 - Shopify CLI v3.55.3

**Comment by charlespwd** [comment]
```
root: src

extends: :nothing

require: []

include_categories: []

exclude_categories: []

ignore:
  - node_modules/*

ConvertIncludeToRender:
  enabled: true
  ignore: []

LiquidTag:
  enabled: true
  ignore: []
  min_consecutive_statements: 5

MissingTemplate:
  enabled: true
  ignore: []

NestedSnippet:
  enabled: true
  ignore: []
  max_nesting_level: 5

RequiredLayoutThemeObject:
  enabled: true
  ignore: []

SpaceInsideBraces:
  enabled: true
  ignore: []

SyntaxError:
  enabled: true
  ignore: []

TemplateLength:
  enabled: true
  ignore: []
  max_length: 500
  # Exclude content of {% schema %} in line count
  exclude_schema: true
  # Exclude content of {% stylesheet %} in line count
  exclude_stylesheet: true
  # Exclude content of {% javascript %} in line count
  exclude_javascript: true

UnknownFilter:
  enabled: true
  ignore: []

UnusedAssign:
  enabled: true
  ignore: []

UnusedSnippet:
  enabled: true
  ignore: []

MatchingSchemaTranslations:
  enabled: true
  ignore: []

MatchingTranslations:
  enabled: true
  ignore: []

DefaultLocale:
  enabled: true
  ignore: []

TranslationKeyExists:
  enabled: true
  ignore: []

ValidHTMLTranslation:
  enabled: true
  ignore: []

ValidJson:
  enabled: true
  ignore: []

ValidSchema:
  enabled: true
  ignore: []

MissingRequiredTemplateFiles:
  enabled: true
  ignore: []

UndefinedObject:
  enabled: true
  ignore: []
  exclude_snippets: true

RequiredDirectories:
  enabled: true
  ignore: []

DeprecatedFilter:
  enabled: true
  ignore: []

DeprecateLazysizes:
  enabled: true
  ignore: []

DeprecateBgsizes:
  enabled: true
  ignore: []

MissingEnableComment:
  enabled: true
  ignore: []

ParserBlockingJavaScript:
  enabled: true
  ignore: []

ParserBlockingScriptTag:
  enabled: true
  ignore: []

AssetSizeJavaScript:
  enabled: false
  threshold_in_bytes: 10_000
  ignore: []

AssetSizeCSS:
  enabled: false
  threshold_in_bytes: 100_000
  ignore: []

AssetSizeCSSStylesheetTag:
  enabled: false
  threshold_in_bytes: 100_000
  ignore: []

ImgWidthAndHeight:
  enabled: true
  ignore: []

RemoteAsset:
  enabled: true
  ignore: []

AssetUrlFilters:
  enabled: true
  ignore: []

ContentForHeaderModification:
  enabled: true
  ignore: []

ImgLazyLoading:
  enabled: true
  ignore: []

HtmlParsingError:
  enabled: true
  ignore: []

AssetSizeAppBlockJavaScript:
  enabled: false
  ignore: []
  threshold_in_bytes: 10_000

AssetSizeAppBlockCSS:
  enabled: false
  ignore: []
  threshold_in_bytes: 100_000
  ```
  
  This .theme-check.yml file is enough to reproduce. Looks related to `ignore_missing` being a required setting for the `MissingTemplate` check when it should be optional.
